# Generated by Django 5.2 on 2025-04-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15)),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
                'unique_together': {('gstin', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='GSTR2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15)),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
                'unique_together': {('gstin', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='GSTR3B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('outward_supplies', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inward_supplies', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sgst_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('igst_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst_input', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sgst_input', models.DecimalField(decimal_places=2, max_digits=15)),
                ('igst_input', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_tax_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('period',)},
            },
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_income', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'category'],
                'unique_together': {('category', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
            options={
                'ordering': ['account__code'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
